name: pull_request_check
on:
  pull_request:
    branches:
      - main
      - dev
      - hotfix/**
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.0.9
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 24.18.0
          cache: "pnpm"
      - name: install
        run: pnpm install --frozen-lockfile
        env:
          CI: true
      - name: check
        run: pnpm check
        env:
          CI: true
